// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mewnelmfqsraeiavfvmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ld25lbG1mcXNyYWVpYXZmdm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTYyNzYsImV4cCI6MjA2NjY3MjI3Nn0.RJOzcVzPetw1NPcCcYeIYPenGoZOV53QufLZcWJEql0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});