// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbimikyjhyewlssnaegl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiaW1pa3lqaHlld2xzc25hZWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTA3NTYsImV4cCI6MjA2NzcyNjc1Nn0.CFRWvEcR9P5YNqHwI1wJ7qsCTuGTO_MwRAq5nhRr3xo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});